### ISSUE TITLE
Working of Non-Blocking Loads

### ISSUE THREAD

**Issue by vignajeth** [chipsalliance/Cores-SweRV-EH2#23]
Hi,
    When I run hello world assembly code, I notice that STDOUT data moves out of LSU through non-blocking loads.

I would like to know how the core decides that it can move the data through non-blocking load ports 

I was unable to get much information about non-blocking loads from PRM, the PRM I think just has registers that can point out during non-blocking load bus errors.

```
        79 :      #20 0 00000042 00010217  tp=00010042 ; auipc   tp,0x10000
        80 :      #21 0 00000046 fbe20213  tp=00010000 ; addi    tp,tp,-66
        80 :      #22 0 0000004a 0000a821              ; c.j     0x62
        85 :      #23 0 00000062 00020283              ; lb      t0,0(tp) [00010000]
        87 :          0                    t0=0000002d ; nbL       <--------------------------------- Here
        93 :      #24 0 00000066 00518023              ; sb      t0,0(gp) [d0580000]
        93 :      #25 0 0000006a 00000205  tp=00010001 ; c.addi  tp,1
        94 :      #26 0 0000006c fe029be3              ; bne     t0,zero,0x62
        99 :      #27 0 00000062 00020283              ; lb      t0,0(tp) [00010001]
       101 :          0                    t0=0000002d ; nbL       <--------------------------------- Here
       107 :      #28 0 00000066 00518023              ; sb      t0,0(gp) [d0580000]
```

Thanks

**Comment by aprnath** [comment]
Non-blocking loads are a micro-architectural feature for performance improvement. They are not SW or architecturally visible, hence not mentioned in detail in the Programmer's reference Manual.

All loads to external memory are treated as non-blocking. The core issues and commits them without waiting for data to be returned. However, it keeps track of register dependencies, and blocks subsequent instruction that consume the data from the load's destination register from being issued into the pipe until dependent loads return data. This allows a certain small "out-of-order"ness to the core to give a performance boost.

**Comment by vignajeth** [comment]
Thanks for your reply
I would like to see this performance boost by running the core with and without non blocking loads (nbL), but I find no flags to turn on/off this feature

do you think this feature can be disabled in RTL ?, I tried few ways but it did not work,  can you point me to the trigger points ?

I also notice that the nbL is tighly linked with lsu_buffer's FSM and it moves from IDLE -> CMD -> RESP -> DONE for every nbL, it would be great if you can give a small explanation how the lsu_buffer and writepointer (wrptr) in it works,

**Comment by aprnath** [comment]
No, there is no way to disable non-blocking loads per se and convert those to blocking loads, without modifying the RTL.
Now if you mark the region as IO, via MRAC, you get a much more aggressive serialization of loads, which is a much bigger hammer than what you are looking to find.

One way to see performance impact is craft your tests in such a way that you force adjacent dependent instructions after every load. Then move those dependent instructions further away (1-N slots), with non-dependent instructions in between. You should see the difference. Pipeline keeps on issuing/committing past the longer latency load, and only blocks when a dependent instruction is seen.

The mechanism is handled between the DEC and LSU using a tag and CAM mechanism, with DEC doing the work of tracking NB loads outstanding to destinations. Dependent instructions are stalled if one of it sources exist as a pending load in the nb CAM. In case of a WAR case (a write after the load to the same register), the dependency is cleared - the load data, when it returns will be discarded, since the dest register was subsequently updated by another later instruction.
