### ISSUE TITLE
unused csr_perfv{a to i} in decoder

### ISSUE THREAD

**Issue by vignajeth** [chipsalliance/Cores-SweRV-EH2#24]
Hi,
   I notice that in _csrdecode_ file the .definition has CSR Address Map number for csr_perfva to csr_perfvi. However it is not used in .decode.
I think the _csr_decoder_ file should be cleanedup by removing csr_perfva to csr_perfvi  or it should be
```
csr[ csr_perfva    ] = { csr_perfva valid_only }
csr[ csr_perfvb    ] = { csr_perfvb valid_only }
csr[ csr_perfvc    ] = { csr_perfvc valid_only }
csr[ csr_perfve    ] = { csr_perfve valid_only }
csr[ csr_perfvf    ] = { csr_perfvf valid_only }
csr[ csr_perfvg    ] = { csr_perfvg valid_only }
csr[ csr_perfvh    ] = { csr_perfvh valid_only }
csr[ csr_perfvi    ] = { csr_perfvi valid_only }
```
I can also see the generated systemverilog file does not have any code related to csr_perfv{a to f}.

**Comment by aprnath** [comment]
Good question, @vignajeth ! These are actually required to provide legal decode equations, but are unused otherwise. They refer to the RISC-V performance counters that must be decoded as legal, but not required to be supported as implemented CSRs. EH2 implements 4 counters. The others must  be legal and return 0 on reads. The decode equations can’t be removed, or a CSR read/write of counter 7-31 will generate an illegal instruction exception.

**Comment by vignajeth** [comment]
Thanks for your reply,
I was able to find the four counters {mhpmcounter3,4,5,6 and mhpmcounter3h,4h,5h,6h} in the PRM.
I had a quick look at Unprivileged ISA Manual (https://riscv.org/technical/specifications/) and was able to find what you were explaining
![image](https://user-images.githubusercontent.com/22914321/137936663-03ef7697-d5e0-4006-8dbf-ee2b385ccd28.png)
